# Generated by Django 2.2.6 on 2019-10-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('nombre', models.CharField(help_text='Nombre', max_length=50)),
                ('email', models.EmailField(help_text='Email usuario', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Contraseña usuario', max_length=30)),
            ],
        ),
    ]
