# Generated by Django 2.2.6 on 2019-10-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliocatalogo', '0002_auto_20191026_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='año',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(help_text='Genero de la', max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre_pelicula',
            field=models.CharField(help_text='Nombre de pelicula', max_length=60),
        ),
    ]
