# Generated by Django 2.2.6 on 2019-11-01 17:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bibliocatalogo', '0004_auto_20191030_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='codigo usuario', primary_key=True, serialize=False),
        ),
    ]
