# Generated by Django 2.2.6 on 2019-11-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliocatalogo', '0007_auto_20191101_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pelicula',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
