# Generated by Django 2.2.6 on 2019-11-02 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliocatalogo', '0008_auto_20191102_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_pelicula', models.CharField(help_text='Nombre de pelicula', max_length=60)),
                ('genero', models.CharField(help_text='Genero de la', max_length=100)),
                ('año', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre', max_length=50)),
                ('email', models.EmailField(help_text='Email usuario', max_length=50)),
                ('password', models.CharField(help_text='Contraseña usuario', max_length=30)),
            ],
        ),
    ]
